apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busy3
  name: busy3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busy3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busy3
    spec:
      containers:
        - image: debian
          name: busy-3
          command: [ "/bin/bash", "-c", "sleep 10000;exit 0" ]
          securityContext:
            privileged: true
