apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jdbc
  name: jdbc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jdbc
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jdbc
    spec:
      containers:
      - image: localhost:5000/jdbc:latest
        name: 8-jre
        imagePullPolicy: Never
        env:
        - name: db_url
          value: "jdbc:mysql://mysql/?"
        - name: check
          value: "yes"
        resources:
          limits:
            cpu: 300m
            memory: 200Mi
          requests:
            cpu: 200m
            memory: 100Mi
status: {}
