apiVersion: v1
metadata:
  name: busy2-svc
  namespace: default
  labels:
    app: busy2
spec:
  ports:
    - protocol: UDP
      port: 8080
      targetPort: 8080
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: busy2
  type: NodePort
kind: Service
