apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: pod-delete
  namespace: mysql
spec:
  annotationCheck: 'true'
  engineState: 'active'
  appinfo:
    appns: 'mysql'
    applabel: 'app=mysql'
    appkind: 'deployment'
  chaosServiceAccount: pod-delete-sa
  # use retain to keep the job for debug
  jobCleanUpPolicy: 'delete' 
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '30000'
            # set chaos interval (in sec) as desired
            - name: CHAOS_INTERVAL
              value: '30000'
            # pod failures without '--force' & default terminationGracePeriodSeconds
            - name: FORCE
              value: 'false'
