apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: network-loss
  namespace: mysql
spec:
  annotationCheck: 'true'
  engineState: 'active'
  appinfo:
    appns: 'mysql'
    applabel: 'app=mysql'
    appkind: 'deployment'
  chaosServiceAccount: pod-network-loss-sa
  # use retain to keep the job for debug
  jobCleanUpPolicy: 'delete' 
  experiments:
    - name: pod-network-loss
      spec:
        components:
          env:
            # set chaos duration (in sec) as desired
            - name: TOTAL_CHAOS_DURATION
              value: '60000'
            - name: TARGET_CONTAINER
              value: 'mysql' 
            - name: NETWORK_INTERFACE
              value: 'eth0'                    
            - name: NETWORK_PACKET_LOSS_PERCENTAGE
              value: '100'
